package com.example.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig institutDaoConfig;
    private final DaoConfig veranstaltungDaoConfig;

    private final InstitutDao institutDao;
    private final VeranstaltungDao veranstaltungDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        institutDaoConfig = daoConfigMap.get(InstitutDao.class).clone();
        institutDaoConfig.initIdentityScope(type);

        veranstaltungDaoConfig = daoConfigMap.get(VeranstaltungDao.class).clone();
        veranstaltungDaoConfig.initIdentityScope(type);

        institutDao = new InstitutDao(institutDaoConfig, this);
        veranstaltungDao = new VeranstaltungDao(veranstaltungDaoConfig, this);

        registerDao(Institut.class, institutDao);
        registerDao(Veranstaltung.class, veranstaltungDao);
    }
    
    public void clear() {
        institutDaoConfig.getIdentityScope().clear();
        veranstaltungDaoConfig.getIdentityScope().clear();
    }

    public InstitutDao getInstitutDao() {
        return institutDao;
    }

    public VeranstaltungDao getVeranstaltungDao() {
        return veranstaltungDao;
    }

}
