package com.example.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VERANSTALTUNG.
 */
public class Veranstaltung {

    private Long id;
    private String titel;
    private String inhalt;
    private String mapUrl;
    private String zeit;
    private String ort;
    private String kategorie;
    private Boolean bisDreizehn;
    private Boolean barrierefrei;
    private Boolean wissenschaftsjahr;
    private Boolean jugendliche;
    private Boolean familie;
    private Boolean favorit;
    private String typ;
    private long institutId;

    public Veranstaltung() {
    }

    public Veranstaltung(Long id) {
        this.id = id;
    }

    public Veranstaltung(Long id, String titel, String inhalt, String mapUrl, String zeit, String ort, String kategorie, Boolean bisDreizehn, Boolean barrierefrei, Boolean wissenschaftsjahr, Boolean jugendliche, Boolean familie, Boolean favorit, String typ, long institutId) {
        this.id = id;
        this.titel = titel;
        this.inhalt = inhalt;
        this.mapUrl = mapUrl;
        this.zeit = zeit;
        this.ort = ort;
        this.kategorie = kategorie;
        this.bisDreizehn = bisDreizehn;
        this.barrierefrei = barrierefrei;
        this.wissenschaftsjahr = wissenschaftsjahr;
        this.jugendliche = jugendliche;
        this.familie = familie;
        this.favorit = favorit;
        this.typ = typ;
        this.institutId = institutId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitel() {
        return titel;
    }

    public void setTitel(String titel) {
        this.titel = titel;
    }

    public String getInhalt() {
        return inhalt;
    }

    public void setInhalt(String inhalt) {
        this.inhalt = inhalt;
    }

    public String getMapUrl() {
        return mapUrl;
    }

    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl;
    }

    public String getZeit() {
        return zeit;
    }

    public void setZeit(String zeit) {
        this.zeit = zeit;
    }

    public String getOrt() {
        return ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public String getKategorie() {
        return kategorie;
    }

    public void setKategorie(String kategorie) {
        this.kategorie = kategorie;
    }

    public Boolean getBisDreizehn() {
        return bisDreizehn;
    }

    public void setBisDreizehn(Boolean bisDreizehn) {
        this.bisDreizehn = bisDreizehn;
    }

    public Boolean getBarrierefrei() {
        return barrierefrei;
    }

    public void setBarrierefrei(Boolean barrierefrei) {
        this.barrierefrei = barrierefrei;
    }

    public Boolean getWissenschaftsjahr() {
        return wissenschaftsjahr;
    }

    public void setWissenschaftsjahr(Boolean wissenschaftsjahr) {
        this.wissenschaftsjahr = wissenschaftsjahr;
    }

    public Boolean getJugendliche() {
        return jugendliche;
    }

    public void setJugendliche(Boolean jugendliche) {
        this.jugendliche = jugendliche;
    }

    public Boolean getFamilie() {
        return familie;
    }

    public void setFamilie(Boolean familie) {
        this.familie = familie;
    }

    public Boolean getFavorit() {
        return favorit;
    }

    public void setFavorit(Boolean favorit) {
        this.favorit = favorit;
    }

    public String getTyp() {
        return typ;
    }

    public void setTyp(String typ) {
        this.typ = typ;
    }

    public long getInstitutId() {
        return institutId;
    }

    public void setInstitutId(long institutId) {
        this.institutId = institutId;
    }

}
